### PR TITLE
Java JitPack fixes

### PR DESCRIPTION
**Pull request by letorbi**
Currently the *java-impl* branch won't compile on JitPack due to a number of problems. This PR fixes the following problems:

* JitPack uses Java 8 by default, but we need Java 16. To fix this OpenJDK 16 will be explicitly installed before JitPack actually starts the building process.
* Building the JavaDoc files fails due to incomplete function descriptions. So JavaDoc will be skipped during the JitPack build process for now.

Once this PR is merged, JitPack will be able to compile the *java-impl* branch again.

### CODE REVIEW

**Comment by letorbi** [comment]
Do you think that this MR could be merged as well, now that #61 has been merged? It's quite small and should be easy to test since only the compiling instructions for JitPack are affected.

Or are there any things you are not happy with? Just tell me and I will try to fix them :)

For what it's worth: I'm using my fork (which includes this PR) with JitPack and everything works without problems.

**Comment by JnCrMx** [comment]
I am a little surprised the ``source ~/.sdkman/bin/sdkman-init.sh`` works as a separate command, but this seems like a much cleaner solution.
I will have to fix the JavaDoc eventually, but for now, I will merge this.

**Comment by JnCrMx** [comment]
And thank you very much for your help and contributions! :D

**Comment by letorbi** [comment]
> I am a little surprised the source ~/.sdkman/bin/sdkman-init.sh works as a separate command, but this seems like a much cleaner solution.

I am not an expert on JitPack or SDKMAN, so there might be better ways to implement this...

> And thank you very much for your help and contributions! :D

You are welcome. I actually need the library for [a little project of mine](https://github.com/letorbi/discord-rich-presence-for-processing), so my contributions were not completely altruistic ;)

**Pull request merged**
