### PR TITLE
Support windows32

### PR DESCRIPTION
**Pull request by gravit0**
In Windows, building target/natives32 normally
In Linux, show error without building failure

### CODE REVIEW

**Comment by JnCrMx** [comment]
Oh, this is a little unfortunate as I've also worked on a solution to build the native library for different architectures.

My idea was to use different CMake toolchain files, so it is possible to optionally specify a cross-compiler. That is really useful for me, as I mostly build everything on Linux with mingw.

**Comment by JnCrMx** [comment]
Please have a look at a1a2a496ffab7674398b9f55f5d0db92070cd5c4 and tell me what you think about it.

**Comment by gravit0** [comment]
Building with mingw will add dependencies on the mingw libraries.

**Comment by JnCrMx** [comment]
My pretty default mingw setup doesn't: 
image
I've been building the last two or three releases with mingw and haven't encountered any problems with using them on Windows.

Maybe it links them statically or something like that?

**Comment by gravit0** [comment]
Good! I will wait for the new version

**Pull request closed without merging**
