### PR TITLE
It seemed to me that this would be better, because this is the only…

### PR DESCRIPTION
**Pull request by Kiritron**
…solution when my application started working with the Discord SDK without obvious errors.

### CODE REVIEW

**Comment by JnCrMx** [comment]
I think that issue might lie in the way you included this library into your project.
Are you using Gradle or did you copy the files into your project directory?

**Comment by Kiritron** [comment]
> Are you using Gradle or did you copy the files into your project directory?
I copied the source code of your product into my project.

**Comment by JnCrMx** [comment]
Ok, so the problem is probably that the folder you stored the native libraries in (`native/`) is not part of the class path.

I use the `getResourceAsStream`-Method which tired to find the resource anywhere in the class path. I prefer that, because it makes it possible to load resources from JAR files.

Please try to place the `native/` inside your class path. This could for example be in the `bin/` directory.
If you need help with that, please tell me which IDE you are using.

**Comment by Kiritron** [comment]
Oh. My mistake. Excuse me. I guess I just didn't understand some things. In this case, your code will be the best solution. My bad.

**Pull request closed without merging**
